version: '3'
services:
  php:
    build: ./php
    volumes:
      - ./htdocs:/var/www/html
      - ./htdocs/docker-conf.d:/etc/apache2/sites-enabled
      - ./logs:/etc/apache2/logs
    ports:
      - "80:80"
    depends_on:
      - mysql
      - memcached
      - redis
      - elasticsearch
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
  memcached:
    image: memcached:alpine
    command: memcached -l 0.0.0.0:10051
  redis:
    image: redis:alpine
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db01
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    volumes:
      - ./mysql:/var/lib/mysql
  elasticsearch:
    image: elasticsearch:1.7
    